apiVersion: v1
kind: Service
metadata:
  name: {{ include "elk.fullname" . }}-elasticsearch
  labels:
    {{- include "elk.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  type: ExternalName
  externalName: {{ .Values.elasticsearch.externalHost }}
  ports:
    - port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
      protocol: TCP
      name: http
